# Complete ddockerfile for local development angular application node 20
FROM node:20-alpine

# Create app directory
RUN mkdir /usr/app

RUN mkdir /usr/app/node_modules

WORKDIR /usr/app

# Copy files

COPY src/ ./src

COPY angular.json ./

# COPY ngsw-config.json ./

COPY package.json ./

COPY tailwind.config.js ./

COPY tsconfig.app.json ./

COPY tsconfig.json ./

# Install dependencies

RUN npm install @angular/cli @angular-devkit/build-angular -g

# Expose port 4200

EXPOSE 4200

# Run the app

CMD ["ng" ,"serve" ,"--configuration" ,"development" ,"--host" ,"0.0.0.0" ,"--port" ,"4200" ,"--poll" ,"1000"]
